
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import { ChakraProvider } from '@chakra-ui/react'
import { ApplicationContext } from "./utils/userContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Flipkart",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApplicationContext>
          <Navbar />
          <ChakraProvider>
            {children}
          </ChakraProvider>
        </ApplicationContext>

      </body>
    </html>
  );
}
